In [4]:
# import data set
import numpy as np
import pandas as pd
from sklearn import datasets,neighbors,linear_model

In [33]:
# loading data set
Boston_Data = datasets.load_boston()
print(Boston_Data)
Boston_Data['data'].describe()

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

#This is unstructural data so we can not perform descriptive Analysis

In [6]:
Boston_Data['data'][1]

array([2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
       6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
       1.7800e+01, 3.9690e+02, 9.1400e+00])

In [7]:
Boston_Data['data'][1].data.shape

(13,)

In [8]:
Boston_Data.data.shape

(506, 13)

In [9]:
X_Boston_Data = Boston_Data.data/Boston_Data.data.max()
X_Boston_Data

array([[8.88888889e-06, 2.53164557e-02, 3.24894515e-03, ...,
        2.15189873e-02, 5.58227848e-01, 7.00421941e-03],
       [3.84106892e-05, 0.00000000e+00, 9.94374121e-03, ...,
        2.50351617e-02, 5.58227848e-01, 1.28551336e-02],
       [3.83825598e-05, 0.00000000e+00, 9.94374121e-03, ...,
        2.50351617e-02, 5.52503516e-01, 5.66807314e-03],
       ...,
       [8.54571027e-05, 0.00000000e+00, 1.67791842e-02, ...,
        2.95358650e-02, 5.58227848e-01, 7.93248945e-03],
       [1.54135021e-04, 0.00000000e+00, 1.67791842e-02, ...,
        2.95358650e-02, 5.53375527e-01, 9.11392405e-03],
       [6.66807314e-05, 0.00000000e+00, 1.67791842e-02, ...,
        2.95358650e-02, 5.58227848e-01, 1.10829817e-02]])

In [10]:
y_Boston_Data = Boston_Data.target

In [11]:
n_samples = len(X_Boston_Data)

In [12]:
# Training data of both. x and y
X_train = X_Boston_Data[:int(0.9*n_samples)]
X_train

array([[8.88888889e-06, 2.53164557e-02, 3.24894515e-03, ...,
        2.15189873e-02, 5.58227848e-01, 7.00421941e-03],
       [3.84106892e-05, 0.00000000e+00, 9.94374121e-03, ...,
        2.50351617e-02, 5.58227848e-01, 1.28551336e-02],
       [3.83825598e-05, 0.00000000e+00, 9.94374121e-03, ...,
        2.50351617e-02, 5.52503516e-01, 5.66807314e-03],
       ...,
       [7.15917018e-03, 0.00000000e+00, 2.54571027e-02, ...,
        2.84106892e-02, 5.41617440e-01, 2.42897328e-02],
       [1.16006892e-02, 0.00000000e+00, 2.54571027e-02, ...,
        2.84106892e-02, 5.28649789e-01, 2.35443038e-02],
       [1.33806329e-02, 0.00000000e+00, 2.54571027e-02, ...,
        2.84106892e-02, 9.39521800e-03, 2.63150492e-02]])

In [13]:
y_train = y_Boston_Data[:int(0.9*n_samples)]
y_train

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [14]:
# Testing data for both x and y
X_test = X_Boston_Data[:int(0.9*n_samples)]
X_test

array([[8.88888889e-06, 2.53164557e-02, 3.24894515e-03, ...,
        2.15189873e-02, 5.58227848e-01, 7.00421941e-03],
       [3.84106892e-05, 0.00000000e+00, 9.94374121e-03, ...,
        2.50351617e-02, 5.58227848e-01, 1.28551336e-02],
       [3.83825598e-05, 0.00000000e+00, 9.94374121e-03, ...,
        2.50351617e-02, 5.52503516e-01, 5.66807314e-03],
       ...,
       [7.15917018e-03, 0.00000000e+00, 2.54571027e-02, ...,
        2.84106892e-02, 5.41617440e-01, 2.42897328e-02],
       [1.16006892e-02, 0.00000000e+00, 2.54571027e-02, ...,
        2.84106892e-02, 5.28649789e-01, 2.35443038e-02],
       [1.33806329e-02, 0.00000000e+00, 2.54571027e-02, ...,
        2.84106892e-02, 9.39521800e-03, 2.63150492e-02]])

In [15]:
y_test = y_Boston_Data[:int(0.9*n_samples)]
y_test

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [29]:
# Data Modeling
Knn = neighbors.KNeighborsClassifier()
linear = linear_model.LinearRegression() #leghthbredthfiguresize=lbfgs
linear

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
# Classification Score
#print('Knn Score: %f'% Knn.fit(X_train,y_train).score(X_test,y_test))

In [31]:
# Prediction Score
print('Linear Score: %f'% linear.fit(X_train,y_train).score(X_test,y_test))

Linear Score: 0.741698
