In [24]:
import numpy as np
import pandas as pd
from sklearn import datasets,neighbors,linear_model
import matplotlib.pyplot as plt

In [11]:
#Unstructured 
Cancer_Data=datasets.load_breast_cancer()
print(Cancer_Data)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [12]:
Cancer_Data['data'][1]

array([2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
       8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
       3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
       1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
       1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02])

In [13]:
Cancer_Data.data.shape

(569, 30)

In [14]:
X_Cancer_Data = Cancer_Data.data/Cancer_Data.data.max()
X_Cancer_Data

array([[4.22896098e-03, 2.44005642e-03, 2.88669488e-02, ...,
        6.23883404e-05, 1.08157029e-04, 2.79501646e-05],
       [4.83544899e-03, 4.17724495e-03, 3.12411848e-02, ...,
        4.37235543e-05, 6.46450400e-05, 2.09261871e-05],
       [4.62858486e-03, 4.99529854e-03, 3.05594734e-02, ...,
        5.71227080e-05, 8.49318289e-05, 2.05876822e-05],
       ...,
       [3.90220969e-03, 6.60084626e-03, 2.54583921e-02, ...,
        3.33333333e-05, 5.21391631e-05, 1.83826986e-05],
       [4.84250118e-03, 6.89468735e-03, 3.29337094e-02, ...,
        6.22943112e-05, 9.60742830e-05, 2.91490362e-05],
       [1.82416549e-03, 5.76868829e-03, 1.12646921e-02, ...,
        0.00000000e+00, 6.74894217e-05, 1.65467795e-05]])

In [15]:
y_Cancer_Data = Cancer_Data.target

In [16]:
n_samples = len(X_Cancer_Data)

In [17]:
# Training data of both. x and y
X_train = X_Cancer_Data[:int(0.9*n_samples)]
X_train

array([[4.22896098e-03, 2.44005642e-03, 2.88669488e-02, ...,
        6.23883404e-05, 1.08157029e-04, 2.79501646e-05],
       [4.83544899e-03, 4.17724495e-03, 3.12411848e-02, ...,
        4.37235543e-05, 6.46450400e-05, 2.09261871e-05],
       [4.62858486e-03, 4.99529854e-03, 3.05594734e-02, ...,
        5.71227080e-05, 8.49318289e-05, 2.05876822e-05],
       ...,
       [3.63422661e-03, 5.62999530e-03, 2.44005642e-02, ...,
        5.08462623e-05, 7.08274565e-05, 2.50822755e-05],
       [2.75975552e-03, 3.45322050e-03, 1.79384109e-02, ...,
        2.48236953e-05, 6.12129760e-05, 2.32228491e-05],
       [3.48142924e-03, 3.45557123e-03, 2.22519981e-02, ...,
        1.87000470e-05, 5.48660085e-05, 1.44381758e-05]])

In [18]:
y_train = y_Cancer_Data[:int(0.9*n_samples)]
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [19]:
# Testing data for both x and y
X_test = X_Cancer_Data[:int(0.9*n_samples)]
X_test

array([[4.22896098e-03, 2.44005642e-03, 2.88669488e-02, ...,
        6.23883404e-05, 1.08157029e-04, 2.79501646e-05],
       [4.83544899e-03, 4.17724495e-03, 3.12411848e-02, ...,
        4.37235543e-05, 6.46450400e-05, 2.09261871e-05],
       [4.62858486e-03, 4.99529854e-03, 3.05594734e-02, ...,
        5.71227080e-05, 8.49318289e-05, 2.05876822e-05],
       ...,
       [3.63422661e-03, 5.62999530e-03, 2.44005642e-02, ...,
        5.08462623e-05, 7.08274565e-05, 2.50822755e-05],
       [2.75975552e-03, 3.45322050e-03, 1.79384109e-02, ...,
        2.48236953e-05, 6.12129760e-05, 2.32228491e-05],
       [3.48142924e-03, 3.45557123e-03, 2.22519981e-02, ...,
        1.87000470e-05, 5.48660085e-05, 1.44381758e-05]])

In [20]:
y_test = y_Cancer_Data[:int(0.9*n_samples)]
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [21]:
# Data Modeling
Knn = neighbors.KNeighborsClassifier()
logistic = linear_model.LogisticRegression(solver='lbfgs',max_iter=100,multi_class='multinomial') #leghthbredthfiguresize=lbfgs
logistic

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
# Classification Score
print('Knn Score: %f'% Knn.fit(X_train,y_train).score(X_test,y_test))

Knn Score: 0.945312


In [23]:
# Prediction Score
print('Logistic Score: %f'% logistic.fit(X_train,y_train).score(X_test,y_test))

Logistic Score: 0.882812
