In [5]:
import numpy as np

In [6]:
x=np.array([1,2,3,4])

In [12]:
print(x)

[1 2 3 4]


In [9]:
x.ndim

1

In [13]:
print(type(x))

<class 'numpy.ndarray'>


In [14]:
y=np.array([1,2,3,'n',4])

In [15]:
print(y)

['1' '2' '3' 'n' '4']


In [33]:
z=np.linspace(10,20,10,endpoint=False,retstep=True)

In [34]:
print(z)

(array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]), 1.0)


In [37]:
a=np.arange(10,20,2)

In [39]:
print(a)

[10 12 14 16 18]


In [43]:
b=np.ones((2,2),int)

In [44]:
print(b)

[[1 1]
 [1 1]]


In [45]:
b.ndim

2

In [48]:
c=np.zeros((2,2),complex)

In [50]:
print(c)

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


In [62]:
d=np.random.rand(5,2)

In [63]:
print(d)

[[0.62873734 0.45233836]
 [0.46645486 0.27314791]
 [0.97767741 0.67262118]
 [0.2669482  0.26547009]
 [0.17344961 0.32522479]]


In [64]:
d.ndim

2

In [77]:
l=np.logspace(1,10,5)

In [78]:
print(l)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


###  ** Advantages of numpy array over List **

In [100]:
f=range(1000)

In [101]:
print(f)

range(0, 1000)


In [102]:
timeit sum(f)

14.5 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [103]:
import sys

In [104]:
sys.getsizeof(1)*len(f)

28000

In [105]:
g=np.array(f)

In [106]:
timeit np.sum(g)

4.7 µs ± 540 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [107]:
g.itemsize*g.size

8000

In [110]:
r=np.arange(1,10).reshape(3,3)

In [111]:
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [114]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [118]:
d.shape

(3, 3)

In [119]:
a=np.arange(1,5)

In [120]:
a

array([1, 2, 3, 4])

In [124]:
b=np.arange(5,9)

In [125]:
b

array([5, 6, 7, 8])

In [126]:
c=np.add(a,b) #Element-wise sum

In [127]:
c

array([ 6,  8, 10, 12])

In [128]:
d=np.multiply(a,b)  #Element-wise multiplication

In [129]:
d

array([ 5, 12, 21, 32])

In [130]:
e=np.subtract(a,b) #Element-wise substraction

In [131]:
e

array([-4, -4, -4, -4])

In [132]:
f=np.divide(a,b) #Element-wise division

In [133]:
f

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [134]:
g=np.remainder(a,b) #Element-wise remainder of division

In [135]:
g

array([1, 2, 3, 4])

In [139]:
a=np.arange(1,10).reshape(3,3)

In [140]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
a[2][2]

9

In [142]:
a[2,2]

9

In [143]:
a[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [144]:
a[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
a[: :-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [146]:
a[:,0]

array([1, 4, 7])

In [147]:
a[0,:]

array([1, 2, 3])

In [148]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
a[:2,:2] #Subset of array
# Modify the subset array will automatically update the original array as well.

array([[1, 2],
       [4, 5]])

In [150]:
a[0,0]=50

In [151]:
a

array([[50,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [152]:
b=a.T

In [153]:
b

array([[50,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

In [154]:
c=np.transpose(a)

In [155]:
c

array([[50,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

In [156]:
c_row=np.append(c,[[10,11,12]],axis=0) # Adding along row

In [157]:
c_row

array([[50,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [10, 11, 12]])

In [163]:
c_col=np.append(c,np.array([13,14,15]).reshape(3,1),1) # Adding along column

In [164]:
c_col

array([[50,  4,  7, 13],
       [ 2,  5,  8, 14],
       [ 3,  6,  9, 15]])

In [165]:
a

array([[50,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [168]:
b=np.insert(a,1,[10,11,12],0) # Inserting row-wise array at specified position.

In [169]:
b

array([[50,  2,  3],
       [10, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [170]:
np.delete(b,1,0)

array([[50,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])